# RJ Auto Metadata
# Copyright (C) 2025 Riiicil
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

PROMPT_TEXT = '''Analyze image, generate JSON metadata:
{"title": "minimum 6 words, max 180 chars, descriptive, unique, dont use special characters", "description": "detailed, max 180 chars, unique, dont use special characters", "keywords": ["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category": "pick: Abstract, Animals/Wildlife, Arts, Backgrounds/Textures, Beauty/Fashion, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Industrial, Nature, Objects, People, Science, Signs/Symbols, Sports/Recreation, Technology, Transportation"}'''

PROMPT_TEXT_PNG = '''Analyze main subject only (ignore background), generate JSON:
{"title": "focused on main subject, minimum 6 words, max 180 chars, unique, dont use special characters", "description": "focused on main subject details only, max 180 chars, unique, dont use special characters", "keywords": ["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category": "pick: Abstract, Animals/Wildlife, Arts, Backgrounds/Textures, Beauty/Fashion, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Industrial, Nature, Objects, People, Science, Signs/Symbols, Sports/Recreation, Technology, Transportation"}'''

PROMPT_TEXT_VIDEO = '''
Analyze these video frames comprehensively and generate detailed JSON video metadata:
{"title": "video title, minimum 6 words, max 180 chars, unique, dont use special characters", "description": "video description, max 180 chars, unique, dont use special characters", "keywords": ["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category": "pick: Animals/Wildlife, Arts, Backgrounds/Textures, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Holidays, Industrial, Nature, Objects, People, Religion, Science, Signs/Symbols, Sports/Recreation, Technology, Transportation"}
'''

PROMPT_TEXT_BALANCED = '''Generate balanced JSON metadata:
{"title": "focused, minimum 5 words, max 165 chars, unique, dont use special characters", "description": "clear info, max 165 chars, unique, dont use special characters", "keywords": ["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category": "pick: Abstract, Animals/Wildlife, Arts, Backgrounds/Textures, Beauty/Fashion, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Industrial, Nature, Objects, People, Science, Signs/Symbols, Sports/Recreaction, Technology, Transportation"}'''

PROMPT_TEXT_PNG_BALANCED = '''
Generate balanced JSON metadata:
{"title": "focused on main subject, minimum 5 words, max 165 chars, unique, dont use special characters", "description": "clear info, main subject only, max 165 chars, unique, dont use special characters", "keywords": ["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category": "adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category": "pick: Abstract, Animals/Wildlife, Arts, Backgrounds/Textures, Beauty/Fashion, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Industrial, Nature, Objects, People, Science, Signs/Symbols, Sports/Recreaction, Technology, Transportation"}
'''

PROMPT_TEXT_VIDEO_BALANCED = '''
Generate balanced JSON metadata:
{"title": "video title, minimum 5 words, max 165 chars, unique, dont use special characters", "description": "video description, max 165 chars, unique, dont use special characters", "keywords": ["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category": "adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category": "pick: Animals/Wildlife, Arts, Backgrounds/Textures, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Holidays, Industrial, Nature, Objects, People, Religion, Science, Signs/Symbols, Sports/Recreaction, Technology, Transportation"}
'''

PROMPT_TEXT_FAST = '''Quick JSON: {"title":"minimum 4 words, max 150 chars, unique, dont use special characters", "description":"brief, max 150 chars, unique, dont use special characters", "keywords":["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category":"adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category":"pick one: Abstract, Animals/Wildlife, Arts, Backgrounds/Textures, Beauty/Fashion, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Industrial, Nature, Objects, People, Science, Signs/Symbols, Sports/Recreaction, Technology, Transportation"}'''

PROMPT_TEXT_PNG_FAST = '''Subject JSON: {"title":"main subject, minimum 4 words, max 150 chars, unique, dont use special characters", "description":"subject details only, max 150 chars, unique, dont use special characters", "keywords":["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category":"adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category":"pick one: Abstract, Animals/Wildlife, Arts, Backgrounds/Textures, Beauty/Fashion, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Industrial, Nature, Objects, People, Science, Signs/Symbols, Sports/Recreaction, Technology, Transportation"}'''

PROMPT_TEXT_VIDEO_FAST = '''Video JSON: {"title":"video action, minimum 4 words, max 150 chars, unique, dont use special characters", "description":"video summary, max 150 chars, unique, dont use special characters", "keywords":["Give me 60 unique single-word keywords, all relevant to the image, no multi-word phrases. Array"], "adobe_stock_category":"adobe_stock_category": "pick number and name: 1.Animals, 2.Architecture, 3.Business, 4.Drinks, 5.Environment, 6.Mind, 7.Food, 8.Graphics, 9.Leisure, 10.Industry, 11.Landscapes, 12.Lifestyle, 13.People, 14.Plants, 15.Religion, 16.Science, 17.Social, 18.Sports, 19.Technology, 20.Transport, 21.Travel", "shutterstock_category":"pick one: Animals/Wildlife, Arts, Backgrounds/Textures, Buildings/Landmarks, Business/Finance, Education, Food and drink, Healthcare/Medical, Holidays, Industrial, Nature, Objects, People, Religion, Science, Signs/Symbols, Sports/Recreaction, Technology, Transportation"}''' 